---
- name: Check if geoipupdate is already installed
  ansible.builtin.stat:
    path: "{{ geoipupdate_path }}"
  register: _geoipupdate

- name: Get geoipupdate installed version
  ansible.builtin.command: "{{ geoipupdate_path }} --version"
  changed_when: false
  when: _geoipupdate.stat.exists
  register: _geoipupdate_version

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  when: _geoipupdate_version is skipped or geoipupdate_version not in _geoipupdate_version.stderr

- name: Include configuration tasks
  ansible.builtin.include_tasks: configure.yml
