---
- name: Check if geoipupdate is already installed
  stat:
    path: "{{ geoipupdate_path }}"
  register: _geoipupdate

- name: Get geoipupdate installed version
  command: "{{ geoipupdate_path }} --version"
  changed_when: false
  when: _geoipupdate.stat.exists
  register: _geoipupdate_version

- include_tasks: setup.yml
  when: _geoipupdate_version is skipped or geoipupdate_version not in _geoipupdate_version.stdout

- include_tasks: configure.yml
