---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ansible-role-geoipupdate-debian-9
    image: debian:9
  - name: ansible-role-geoipupdate-debian-10
    image: debian:10
  - name: ansible-role-geoipupdate-ubuntu-1604
    image: ubuntu:16.04
  - name: ansible-role-geoipupdate-ubuntu-1804
    image: ubuntu:18.04

lint:
  name: yamllint

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  ansible_args:
<<<<<<< HEAD
<<<<<<< HEAD
    - -e geoipupdate_account_id=${MAXMIND_USER}
=======
    - -e geoipupdate_account_id=${MAXMIND_ACCOUNT}
>>>>>>> test
=======
    - -e geoipupdate_account_id=${MAXMIND_USER}
>>>>>>> test
    - -e geoipupdate_license_key=${MAXMIND_KEY}

verifier:
  name: testinfra
  lint:
    name: flake8
