---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

platforms:
  - name: ansible-role-geoipupdate-debian-11
    image: debian:11
  - name: ansible-role-geoipupdate-debian-12
    image: debian:12
  - name: ansible-role-geoipupdate-ubuntu-2204
    image: ubuntu:22.04
  - name: ansible-role-geoipupdate-ubuntu-2404
    image: ubuntu:24.04

provisioner:
  name: ansible
  ansible_args:
    - -e geoipupdate_account_id=${MAXMIND_USER}
    - -e geoipupdate_license_key=${MAXMIND_KEY}

verifier:
  name: testinfra
